default:
    image: node
    
workflow:
  rules:
    # Run on Merge requests
    - if: $CI_MERGE_REQUEST_IID
    # Run when triggered by upstream project (coresdk)
    - if: $CI_PIPELINE_SOURCE == 'pipeline'
    # Run when triggered by API (Jenkins from Gerrit styles repo)
    - if: $CI_PIPELINE_SOURCE == 'api'
    # Run this for release
    - if: '$CI_PIPELINE_SOURCE == "web"'
    # Run this for post-submit jobs
    - if: '$CI_COMMIT_BRANCH == "master"'   
    - if: $CI_EXTERNAL_PULL_REQUEST_IID
    
stages: 
    - build
    - test
    - deploy

build:
    stage: build
    interruptible: true
    script:
        - node --version
        - yarn --version
        #- npm --version

test:
    stage: test
    interruptible: true
    script:
        - node --version
    
